### PR TITLE
implement i18n

### PR DESCRIPTION
**Pull request by alvarosamudio**
i18n was implemented for the internationalization of the project and was fully translated into Spanish.

### CODE REVIEW

**Comment by dependon** [comment]
I didn't find the content about translation in the. TS file. Do you mean you need to support Spanish? I will change the default language to English, and then use translation to derive Chinese or Spanish and so on. What do you think

**Comment by dependon** [comment]
I changed the program to English by default, and added a translation. In version 1.0.6, deepin V2 0.2.1

**Comment by dependon** [comment]
image

**Comment by dependon** [comment]
But I'm not sure if this translation is correct

**Comment by dependon** [comment]
Screenshot_fantascene-dynamic-wallpaper_20210602195339
this is English version.

**Comment by alvarosamudio** [comment]
le 

> I didn't find the content about translation in the. TS file. Do you mean you need to support Spanish? I will change the default language to English, and then use translation to derive Chinese or Spanish and so on. What do you think

I will take a look at the Spanish translations again and let you know if everything is correct.

**Comment by dependon** [comment]
ok，thanks

**Comment by alvarosamudio** [comment]
create a new PR with updated translations https://github.com/dependon/fantascene-dynamic-wallpaper/pull/10

**Pull request closed without merging**
